### ISSUE TITLE
osx/iterm/v0.4.1 using Ctrl+C to exit the cli app makes the text cursor disappear

### ISSUE THREAD

**Issue by mrozbarry** [enquirer/enquirer#13] opened 2017-03-24 12:54 UTC
To fix the problem, I'm able to re-run my app and do a proper exit with a list option and process.exit(). Any chance of getting something like `enquirer.cleanup()` to close any pipes/handles that aren't cleaned up when an `.ask` is done?

**Comment by jonschlinkert** [comment] 2017-03-24 13:02
> Any chance of getting something like enquirer.cleanup() to close any pipes/handles that aren't cleaned up when an .ask is done?

@doowb and I just talked about something related (I believe). @doowb did you mention having a local branch with a fix for this?

**Comment by mrozbarry** [comment] 2017-03-24 13:03
Wow you guys are fast :)

**Comment by mrozbarry** [comment] 2017-03-24 13:04
Also, it appears that enquirer is globbling up my `Ctrl + c` and `process.on("SIGINT", function () { console.log("Ctrl+C pressed!") })` doesn't fire - not sure if this is a related problem, or a separate issue, though.

**Comment by doowb** [comment] 2017-03-24 14:12
> just talked about something related (I believe).

There's a bug in `prompt-base` that in some situations the input stream is held open causing the app to stay open, requiring the use of `Ctrl + c`. I have a fix for that and I'll get it pushed up soon.

>  it appears that enquirer is globbling up my `Ctrl + c` and `process.on("SIGINT", function () { console.log("Ctrl+C pressed!") })` doesn't fire

This has something to do with `readline`, but I don't remember off the top of my head how it's handled. I'll look into it to see if this is a problem. It might be that we need to handle `Ctrl + c` explicitly in `enquirer`.

We're using `cli-cursor` to hide the cursor in some prompts, which is supposed to handle restoring the cursor when the process exits. Which node version are you using and are you able to capture a gif showing the bug?

**Comment by jonschlinkert** [comment] 2017-03-24 18:47
> Wow you guys are fast :)

haha, well let's see how fast we can get that fix shipped. Sorry it's taking so long, we wanted to do more testing locally before we pushed it up. thanks!

**Comment by jonschlinkert** [comment] 2017-03-24 18:49
> It might be that we need to handle Ctrl + c explicitly in enquirer.

I think we already explicitly handle it somewhere, probably readline-utils, but we probably are not doing anything to hide or show the cursor. A pr for this would be great, or we'll try to get this fixed asap.

**Comment by jonschlinkert** [comment] 2017-05-11 03:45
I'm pretty sure this was fixed. We can re-open or create a new issue if anyone still has a problem with this

**Comment by vjpr** [comment] 2018-11-17 01:39
I'm still seeing this.

**Comment by vjpr** [comment] 2018-11-17 03:05
I am running my app as a child process of another Node app using `spawn`. In the parent app, I am listening to SIGINT, and then forwarding the process kill command to the child. Maybe its is some interaction with that.

**Comment by nahtnam** [comment] 2018-11-28 06:32
I am having a similar issue. I can provide an example if no one else is able to reproduce it.

**Comment by jonschlinkert** [comment] 2018-11-28 07:01
> I am having a similar issue. I can provide an example if no one else is able to reproduce it.

That would be great, any additional info will help. Thanks!

**Comment by nahtnam** [comment] 2018-11-28 07:03
@jonschlinkert Excuse the mess, I just extracted this from my project. Select "client" and then press `ctrl + c`.

```js
const { prompt } = require('enquirer');

const contractor = async () => {
  const register = async () => {
    menu();
  }
  const menu = async () => {
    const { action } = await prompt({
      type: 'select',
      name: 'action',
      message: 'what would you like to do?',
      choices: ['register', 'update', 'mine'],
      initial: 'register',
    });
    switch (action) {
      case 'register': {
        await register();
        break;
      }
      case 'update': {
        console.log('update');
        break;
      }
      case 'mine': {
        console.log('mine');
        break;
      }
      default: {
        console.log('mine');
        break;
      }
    }
  }
  menu();
}

const client = async () => {
  const query = async () => {
    menu();
  }
  const menu = async () => {
    const { action } = await prompt({
      type: 'select',
      name: 'action',
      message: 'what would you like to do?',
      choices: ['query', 'check'],
      initial: 'query',
    });
    switch (action) {
      case 'query': {
        await query();
        break;
      }
      case 'check': {
        console.log('check');
        break;
      }
      default: {
        await query();
        break;
      }
    }
  }
  menu();
}

const program = async () => {
  const { type } = await prompt({
    type: 'select',
    name: 'type',
    message: 'would you like to start a contractor or client?',
    choices: ['contractor', 'client'],
    initial: 'client',
  });

  if (!type || type === 'contractor') {
    return contractor();
  }
  return client();
}

program().catch((err) => {
  console.log(err);
});
```

**Comment by jonschlinkert** [comment] 2018-12-15 22:14
@nahtnam thanks so much for the detail! I'm sorry I didn't see your reply until now. 

I'll spend some time reviewing to see if I can wrap my brain around this. Thanks again.

**Comment by nahtnam** [comment] 2018-12-16 00:58
Hello!

Thanks for taking a look, it makes sense now. I think the opposite would be a better idea. Most people expect the program to quit after you press `ctrl + c`, but there are definitely applications where you wouldn't want to be allowed to quit. I think it would be better if by default it quit, and you can add a hook to do something else on `ctrl + c`. However, if it is changed, I think you should bump the version up by `1.0` since it would be a breaking change. As for now, I think adding `prompt.on('cancel', () => process.exit());` to the docs would be the best idea.

**Comment by jonschlinkert** [comment] 2018-12-16 16:38
> I think the opposite would be a better idea. Most people expect the program to quit after you press `ctrl + c`,

I think this makes sense. I'll get a patch pushed up soon.

**Comment by nahtnam** [comment] 2018-12-16 19:45
Sounds good, thank you!

**Comment by mikeerickson** [comment] 2018-12-16 19:47
This is proof that @jonschlinkert and @doowb have put a lot of thought into making this a great tool for CLI developers.  And the customer service is top notch

**Comment by nahtnam** [comment] 2018-12-16 19:48
Haha, I agree! I wouldn't call it customer service though, maybe community service instead.

**Closed** 2018-12-28 05:16 UTC
Labels: bug
