### ISSUE TITLE
Series of Prompts and ctrl + c

### ISSUE THREAD

**Issue by hipstersmoothie** [enquirer/enquirer#94] opened 2018-12-16 09:20 UTC
I currently have a series of prompts that ask the user if they want to run more prompts. So something like:

```ts
const getAnotherOption: { value?: boolean } = await prompt({
  type: 'confirm',
  name: 'value',
  message: 'Would you like to add some option?',
  initial: 'no'
});

if (getAnotherOption.value) {
  // do another prompt
}
```

if a user presses ctrl+c during on prompt it just goes to the next one. I've tried catching or seeing if enquirer returns something when this happens but I can't find anything.

It would be awesome if enquirer returned something in this case so I can exit the overall script.

```js
{ _userExited: true }
```

NOTE: the user can hit ctrl+d but that isn't as well known i think

**Comment by jonschlinkert** [comment] 2018-12-16 16:40
I think this is a duplicate of https://github.com/enquirer/enquirer/issues/13. 

For the short-term fix, see https://github.com/enquirer/enquirer/issues/13#issuecomment-447602031. I'll be pushing up a patch to make this work as expected.

**Comment by hipstersmoothie** [comment] 2018-12-16 21:36
@jonschlinkert Is the following supposed to work right now? Or is it a part of the patch?

```js
prompt.on('cancel', () => {
  console.log('here');
  process.exit();
});
```

I tried adding it to my application and it did not seem to fire. I added these lines of line 10 in this file https://github.com/intuit/auto-release/blob/master/src/init.ts

**Comment by hipstersmoothie** [comment] 2018-12-16 21:39
Currently a user has to hit ctrl+c 4 times to exit the 4 prompts that run

<img width="1029" alt="screen shot 2018-12-16 at 1 39 01 pm" src="https://user-images.githubusercontent.com/1192452/50059158-0e3a2a00-0138-11e9-9ffe-6ceec8db9e7d.png">

**Comment by jonschlinkert** [comment] 2018-12-16 23:36
> Is the following supposed to work right now? Or is it a part of the patch?

Hmm, it should work. 

> Currently a user has to hit ctrl+c 4 times to exit the 4 prompts that run

That would be annoying. 

I'll push up a patch this evening to make it cancel all prompts by default. I think it's pretty clear that most users would expect that.

**Comment by jonschlinkert** [comment] 2018-12-17 14:17
@hipstersmoothie I fixed this last night but got too tired to wrap everything up. I'll try to do this today.

**Comment by hipstersmoothie** [comment] 2018-12-18 06:15
No rush! Thanks for the awesome code ❤️

**Closed** 2018-12-28 05:16 UTC

**Comment by hipstersmoothie** [comment] 2018-12-31 21:20
It worked! @jonschlinkert thanks
